font=Iosevka:size=13
line-height=24
fields=name,generic,comment,categories,filename,keywords
terminal=alacritty
prompt="❯   "
layer=overlay
lines=10


[colors]
background=3c3836e6
text=d79921ff
match=b16286ff
selection=bdae93bf
selection-match=b16286ff
selection-text=fabd2fff
border= FFC300ff

; [colors]
; background=1e1e2edd
; text=cdd6f4ff
; match=f38ba8ff
; selection=585b70ff
; selection-match=f38ba8ff
; selection-text=cdd6f4ff
; border=b4befeff


; [colors]
; background      = 2d353bff
; text            = d3c6aaff
; match           = e67e80ff
; selection       = 585b70ff
; selection-text  = a7c080ff
; selection-match = e67e80ff
; border          = e67e80ff



[border]
radius=5
width=1

