theme = "gruvbox"

[editor]
line-number = "relative"
bufferline = "always"


[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[keys.normal]
A-q = ":reflow"
A-L = "switch_to_lowercase"
A-U = "switch_to_uppercase"
A-x = "extend_to_line_bounds"
X = ["extend_line_up", "extend_to_line_bounds"]

[keys.select]
A-x = "extend_to_line_bounds"
X = ["extend_line_up", "extend_to_line_bounds"]

[keys.insert]
A-q = ":reflow"

[keys.normal.g]
x = ":buffer-close"
j = "jump_backward"
k = "jump_forward"

[keys.normal.space]
l = ":toggle lsp.display-inlay-hints"

[keys.normal.backspace]
b = ":sh zellij run -f -- cargo build"
d = ":sh zellij run -f -- cargo run"
r = ":sh zellij run -f -- cargo run --release"
g = ":sh zellij run -fc -- gitui"
c = ":sh zellij run -f -- nu -c 'cordova prepare android; cordova run android'"

