[[language]]
name = "rust"
language-servers = ["rust-analyzer"]

[language.debugger]
command = "lldb-dap"
name = "lldb-dap"
transport = "stdio"

[[language.debugger.templates]]
name = "binary"
request = "launch"
completion = [ { name = "binary", completion = "filename" } ]
args = { program = "{0}" }



[[language]]
name = "python"
language-servers = [ "pyright", "ruff" ]

[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"

[language-server.ruff]
command = "ruff-lsp"

[language-server.ruff.config.settings]
args = ["--ignore", "E501"]

[language.formatter]
command = "ruff"
args = ["format"]

[language-server.phpactor]
command = "phpactor"
args = [ "language-server" ]
config = { "language_server_completion.trim_leading_dollar" = true, "language_server_php_cs_fixer.enabled" = true, "language_server_php_cs_fixer.show_diagnostics" = false, "language_server_php_cs_fixer.bin" = "/home/mentalist/.local/bin/php-cs-fixer"}

[[language]]
name = "php"
language-servers = [ "phpactor" ]
